apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: getfood
  name: getfood
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: getfood
  strategy: {}
  template:
    metadata:
      labels:
        deployment: getfood
        app.kubernetes.io/part-of: foods
    spec:
      initContainers:
      - name: init-createdb
        image: postgres:14
        command: ["psql", "postgresql://postgres:postgres@postgresql", "-f", "/etc/rsalbums/create_database.sql"]
        volumeMounts:
        - name: albums-volume
          mountPath: /etc/rsalbums

      - name: init-builddb
        image: postgres:14
        command: ["psql", "postgresql://postgres:postgres@postgresql/foods", "-f", "/etc/rsalbums/build_tables.sql"]
        volumeMounts:
        - name: albums-volume
          mountPath: /etc/rsalbums

      - name: init-populatedb
        image: postgres:14
        command: ["psql", "postgresql://postgres:postgres@postgresql/foods", "-c", "\\copy food FROM '/etc/rsalbums/fooddisplaytable.csv' CSV HEADER;"]
        volumeMounts:
        - name: albums-volume
          mountPath: /etc/rsalbums

      volumes:
      - name: albums-volume
        configMap:
          name: db-config